### ISSUE TITLE
Automated Testing Error Removed Vertex

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-basics#16]
fuzztesting requirejs on phettest:
```
Uncaught Error: Assertion failed: Removed vertex should not have any listeners
Error: Assertion failed: Removed vertex should not have any listeners
    at window.assertions.assertFunction (http://phettest.colorado.edu/assert/js/assert.js:23:13)
    at Circuit.inherit.connect (http://phettest.colorado.edu/circuit-construction-kit-basics/js/common/model/Circuit.js?bust=1457466170934:225:17)
    at CircuitNode.inherit.endDrag (http://phettest.colorado.edu/circuit-construction-kit-basics/js/common/view/CircuitNode.js?bust=1457466170934:300:22)
    at FixedLengthComponentNode.inputListener.SimpleDragHandler.end (http://phettest.colorado.edu/circuit-construction-kit-basics/js/common/view/FixedLengthComponentNode.js?bust=1457466170934:76:21)
    at SimpleDragHandler.inherit.endDrag (http://phettest.colorado.edu/scenery/js/input/SimpleDragHandler.js?bust=1457466170934:165:26)
    at Object.SimpleDragHandler.dragListener.up (http://phettest.colorado.edu/scenery/js/input/SimpleDragHandler.js?bust=1457466170934:74:19)
    at Input.inherit.dispatchToPointer (http://phettest.colorado.edu/scenery/js/input/Input.js?bust=1457466170934:811:29)
    at Input.inherit.dispatchEvent (http://phettest.colorado.edu/scenery/js/input/Input.js?bust=1457466170934:784:14)
    at Input.inherit.upEvent (http://phettest.colorado.edu/scenery/js/input/Input.js?bust=1457466170934:654:14)
    at Input.inherit.mouseUp (http://phettest.colorado.edu/scenery/js/input/Input.js?bust=1457466170934:326:14)
    at Display.extend.fuzzMouseEvents (http://phettest.colorado.edu/scenery/js/display/Display.js?bust=1457466170934:1091:25)
```

**Comment by samreid** [comment]
I did not see this problem in latest master:
![image](https://cloud.githubusercontent.com/assets/679486/14048216/7990fe32-f272-11e5-8e80-6ff4e52cbfcb.png)

**Comment by phet-steele** [comment]
Another occurrence on 3/29 automated test (10:00 AM).

**Comment by samreid** [comment]
After running the test twice, I saw the assertion error occur.

**Comment by samreid** [comment]
The extra listener is added by Circuit.js:

```js
    var circuitChangedEmitterFunction = function() {
      circuit.circuitChangedEmitter.emit();
    };
```

**Comment by samreid** [comment]
This problem is annoyingly difficult to duplicate, even after removing unrelated user interface components.

**Comment by phet-steele** [comment]
@samreid happened two more times on 4/5/2016. The assertion in the commit immediately above was not thrown.

**Comment by phet-steele** [comment]
Actually, the above stack trace only refers to one line in Circuit.js. Today's error was different in that it referred to this line 331 (in Circuit.js), too. Hope it helps.

**Comment by phet-steele** [comment]
Probably safer if I just show you it :smile: 
```
Uncaught Error: Assertion failed: Removed vertex should not have any listeners
Error: Assertion failed: Removed vertex should not have any listeners
    at window.assertions.assertFunction (http://phettest.colorado.edu/assert/js/assert.js:23:13)
    at Circuit.inherit.connect (http://phettest.colorado.edu/circuit-construction-kit-basics/js/common/model/Circuit.js?bust=1459873317061:342:19)
    at Circuit.inherit.connect (http://phettest.colorado.edu/circuit-construction-kit-basics/js/common/model/Circuit.js?bust=1459873317061:331:14)
    at CircuitNode.inherit.endDrag (http://phettest.colorado.edu/circuit-construction-kit-basics/js/common/view/CircuitNode.js?bust=1459873317061:380:22)
    at FixedLengthCircuitElementNode.inputListener.SimpleDragHandler.end (http://phettest.colorado.edu/circuit-construction-kit-basics/js/common/view/FixedLengthCircuitElementNode.js?bust=1459873317061:133:21)
    at SimpleDragHandler.inherit.endDrag (http://phettest.colorado.edu/scenery/js/input/SimpleDragHandler.js?bust=1459873317061:165:26)
    at Object.SimpleDragHandler.dragListener.up (http://phettest.colorado.edu/scenery/js/input/SimpleDragHandler.js?bust=1459873317061:74:19)
    at Input.inherit.dispatchToPointer (http://phettest.colorado.edu/scenery/js/input/Input.js?bust=1459873317061:811:29)
    at Input.inherit.dispatchEvent (http://phettest.colorado.edu/scenery/js/input/Input.js?bust=1459873317061:784:14)
    at Input.inherit.upEvent (http://phettest.colorado.edu/scenery/js/input/Input.js?bust=1459873317061:654:14)
    at Input.inherit.mouseUp (http://phettest.colorado.edu/scenery/js/input/Input.js?bust=1459873317061:326:14)
    at Display.extend.fuzzMouseEvents (http://phettest.colorado.edu/scenery/js/display/Display.js?bust=1459873317061:1099:25)
```

**Comment by phet-steele** [comment]
This happened yet again on 4/12/2016.

**Comment by samreid** [comment]
The vertex positionProperty is somehow getting two similar but different listeners:

![image](https://cloud.githubusercontent.com/assets/679486/14768191/68c6bbe4-09f8-11e6-8296-4cd9744c23b5.png)

**Comment by samreid** [comment]
Ah, the problem is that the black box vertices have two circuits, and are only getting removed from one of them.

**Comment by samreid** [comment]
Fixed above, @phet-steele please repoen if this bug occurs again.
